export const CREATE = 'CREATE'
export const UPDATE = 'UPDATE'
export const FETCH = 'FETCH_ALL'
export const LIKE = 'LIKE'
export const DELETE = 'DELETE'
export const AUTH = 'AUTH'
export const LOGOUT = 'LOGOUT'